# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twinu_core.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='twinu_core.proto',
  package='twinu',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10twinu_core.proto\x12\x05twinu\"t\n\nTwNodeInfo\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x11\n\tnode_type\x18\x03 \x01(\t\x12\x16\n\x0eglobal_ip_port\x18\x04 \x01(\t\x12\x15\n\rlocal_ip_port\x18\x05 \x01(\t\"F\n\x0bTwNodeQuery\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x11\n\tnode_type\x18\x03 \x01(\t\"*\n\rQueryProvider\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1c\n\x08StepInfo\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\"\x12\n\x02OK\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0c\x43lockMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2\x8e\x01\n\x05Twinu\x12)\n\x07GetInfo\x12\t.twinu.OK\x1a\x11.twinu.TwNodeInfo\"\x00\x12\x34\n\tQueryNode\x12\x12.twinu.TwNodeQuery\x1a\x11.twinu.TwNodeInfo\"\x00\x12$\n\x04Step\x12\x0f.twinu.StepInfo\x1a\t.twinu.OK\"\x00\x32O\n\x0b\x43lockMaster\x12@\n\x0eSubscribeClock\x12\x13.twinu.ClockMessage\x1a\x13.twinu.ClockMessage\"\x00(\x01\x30\x01\x62\x06proto3'
)




_TWNODEINFO = _descriptor.Descriptor(
  name='TwNodeInfo',
  full_name='twinu.TwNodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='twinu.TwNodeInfo.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='twinu.TwNodeInfo.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_type', full_name='twinu.TwNodeInfo.node_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='global_ip_port', full_name='twinu.TwNodeInfo.global_ip_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_ip_port', full_name='twinu.TwNodeInfo.local_ip_port', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=143,
)


_TWNODEQUERY = _descriptor.Descriptor(
  name='TwNodeQuery',
  full_name='twinu.TwNodeQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='twinu.TwNodeQuery.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='twinu.TwNodeQuery.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_type', full_name='twinu.TwNodeQuery.node_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=215,
)


_QUERYPROVIDER = _descriptor.Descriptor(
  name='QueryProvider',
  full_name='twinu.QueryProvider',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='twinu.QueryProvider.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='twinu.QueryProvider.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=259,
)


_STEPINFO = _descriptor.Descriptor(
  name='StepInfo',
  full_name='twinu.StepInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='twinu.StepInfo.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=289,
)


_OK = _descriptor.Descriptor(
  name='OK',
  full_name='twinu.OK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='twinu.OK.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=309,
)


_CLOCKMESSAGE = _descriptor.Descriptor(
  name='ClockMessage',
  full_name='twinu.ClockMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='twinu.ClockMessage.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=339,
)

DESCRIPTOR.message_types_by_name['TwNodeInfo'] = _TWNODEINFO
DESCRIPTOR.message_types_by_name['TwNodeQuery'] = _TWNODEQUERY
DESCRIPTOR.message_types_by_name['QueryProvider'] = _QUERYPROVIDER
DESCRIPTOR.message_types_by_name['StepInfo'] = _STEPINFO
DESCRIPTOR.message_types_by_name['OK'] = _OK
DESCRIPTOR.message_types_by_name['ClockMessage'] = _CLOCKMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwNodeInfo = _reflection.GeneratedProtocolMessageType('TwNodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _TWNODEINFO,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.TwNodeInfo)
  })
_sym_db.RegisterMessage(TwNodeInfo)

TwNodeQuery = _reflection.GeneratedProtocolMessageType('TwNodeQuery', (_message.Message,), {
  'DESCRIPTOR' : _TWNODEQUERY,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.TwNodeQuery)
  })
_sym_db.RegisterMessage(TwNodeQuery)

QueryProvider = _reflection.GeneratedProtocolMessageType('QueryProvider', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPROVIDER,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.QueryProvider)
  })
_sym_db.RegisterMessage(QueryProvider)

StepInfo = _reflection.GeneratedProtocolMessageType('StepInfo', (_message.Message,), {
  'DESCRIPTOR' : _STEPINFO,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.StepInfo)
  })
_sym_db.RegisterMessage(StepInfo)

OK = _reflection.GeneratedProtocolMessageType('OK', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.OK)
  })
_sym_db.RegisterMessage(OK)

ClockMessage = _reflection.GeneratedProtocolMessageType('ClockMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLOCKMESSAGE,
  '__module__' : 'twinu_core_pb2'
  # @@protoc_insertion_point(class_scope:twinu.ClockMessage)
  })
_sym_db.RegisterMessage(ClockMessage)



_TWINU = _descriptor.ServiceDescriptor(
  name='Twinu',
  full_name='twinu.Twinu',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=342,
  serialized_end=484,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='twinu.Twinu.GetInfo',
    index=0,
    containing_service=None,
    input_type=_OK,
    output_type=_TWNODEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryNode',
    full_name='twinu.Twinu.QueryNode',
    index=1,
    containing_service=None,
    input_type=_TWNODEQUERY,
    output_type=_TWNODEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='twinu.Twinu.Step',
    index=2,
    containing_service=None,
    input_type=_STEPINFO,
    output_type=_OK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWINU)

DESCRIPTOR.services_by_name['Twinu'] = _TWINU


_CLOCKMASTER = _descriptor.ServiceDescriptor(
  name='ClockMaster',
  full_name='twinu.ClockMaster',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=486,
  serialized_end=565,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeClock',
    full_name='twinu.ClockMaster.SubscribeClock',
    index=0,
    containing_service=None,
    input_type=_CLOCKMESSAGE,
    output_type=_CLOCKMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOCKMASTER)

DESCRIPTOR.services_by_name['ClockMaster'] = _CLOCKMASTER

# @@protoc_insertion_point(module_scope)
